

services:
  mysql:
    image: mysql:8.0
    container_name: banco-malvader
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco_malvader
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
